Feature/infinity carousel widget
cusdeb-com/hammett pull request #55
Opened 2023-08-22 11:31 UTC by warewarewapain

2023-09-28 13:42 UTC, Themanwhosmellslikesugar requested changes

2023-09-28 13:42 UTC, Themanwhosmellslikesugar commented on hammett/widgets/carousel_widget.py
> +            next_state: int,
Fix the indent it should be 4 instead 8

2023-10-05 14:09 UTC, Themanwhosmellslikesugar approved these changes

2023-11-21 10:40 UTC, eugulixes approved these changes

2023-11-21 10:44 UTC, merged