Explicitly register handlers
cusdeb-com/hammett pull request #64
Opened 2023-08-30 19:26 UTC by eugulixes

2023-09-12 15:37 UTC, Themanwhosmellslikesugar requested changes

2023-09-12 15:37 UTC, Themanwhosmellslikesugar commented on hammett/types.py
> +    typing_handler = 'typing_handler'
Can we replace this with enum.auto()?

2023-09-25 09:26 UTC, Themanwhosmellslikesugar requested changes

2023-09-25 09:26 UTC, Themanwhosmellslikesugar commented on hammett/types.py
> +    typing_handler = auto()
Usually all variants of enum are written in the upper case

2023-09-25 09:34 UTC, Themanwhosmellslikesugar approved these changes

2023-09-25 09:37 UTC, warewarewapain approved these changes

2023-09-25 10:23 UTC, merged