Implement jobs mechanism
cusdeb-com/hammett pull request #65
Opened 2023-09-05 15:37 UTC by warewarewapain

2023-09-26 11:06 UTC, Themanwhosmellslikesugar commented on hammett/core/__init__.py
> +                    )
Move to separete method like `register_handlers`

2023-09-26 11:06 UTC, Themanwhosmellslikesugar commented on demos/screens/__init__.py
Add blank line to the end of file

2023-10-05 14:14 UTC, Themanwhosmellslikesugar requested changes

2023-10-05 15:40 UTC, Themanwhosmellslikesugar approved these changes

2023-10-05 15:40 UTC, eugulixes approved these changes

2023-10-05 15:42 UTC, merged