Make it possible to dynamically form data for RenderConfig
cusdeb-com/hammett pull request #74
Opened 2023-10-05 11:49 UTC by warewarewapain

2023-10-05 11:59 UTC, Themanwhosmellslikesugar requested changes

2023-10-05 11:59 UTC, Themanwhosmellslikesugar commented on hammett/core/screen.py
> +    def get_description(
Make all methods async because we'll can make request to some backend to get description

2023-10-05 17:40 UTC, eugulixes commented on hammett/core/screen.py
> +        context: 'CallbackContext[BT, UD, CD, BD]',    # noqa: ARG002
Add `_` prefix to avoid disabling `ARG002`.

2023-10-18 14:58 UTC, eugulixes approved these changes

2023-10-18 15:01 UTC, merged