Implement interface for switching between Screen states
cusdeb-com/hammett pull request #98
Opened 2024-01-10 09:26 UTC by warewarewapain

2024-01-17 09:30 UTC, Themanwhosmellslikesugar requested changes

2024-01-17 09:30 UTC, Themanwhosmellslikesugar commented on hammett/core/conversation_handler.py
> +            context.user_data['current_state'] = new_state  # type: ignore[index]
add `try...except TypeError`

2024-01-17 09:30 UTC, Themanwhosmellslikesugar commented on hammett/core/screen.py
> +    async def _get_return_state_from_routes(
Move to RouteMixin

2024-02-01 20:31 UTC, eugulixes approved these changes

2024-02-01 20:31 UTC, merged